#!/bin/bash

echo "=== REDEPLOYMENT SCRIPT FOR VEHICLE SALES APP ==="
echo "This script will help redeploy all components with the correct URLs"
echo ""

echo "🔧 CONFIGURATION SUMMARY:"
echo "Backend URL: https://webvehicles-backend.onrender.com"
echo "Frontend Admin: https://vehicle-sales-admin.netlify.app"
echo "Frontend Web: https://vehicle-sales-web.netlify.app"
echo ""

echo "📋 STEPS TO REDEPLOY:"
echo ""

echo "1. BACKEND (Render):"
echo "   - Go to https://dashboard.render.com"
echo "   - Find your service (should be 'webvehicles-backend')"
echo "   - If it doesn't exist, create a new service with:"
echo "     * Name: webvehicles-backend"
echo "     * Repository: https://github.com/KarmaliteHub/vehicle-sales-app"
echo "     * Root Directory: backend"
echo "     * Build Command: ./build.sh"
echo "     * Start Command: gunicorn backend.wsgi:application --bind 0.0.0.0:\$PORT"
echo "   - Set environment variables:"
echo "     * DEBUG=False"
echo "     * ENVIRONMENT=production"
echo "     * CLOUDINARY_CLOUD_NAME=your_cloud_name"
echo "     * CLOUDINARY_API_KEY=your_api_key"
echo "     * CLOUDINARY_API_SECRET=your_api_secret"
echo "   - Deploy the service"
echo ""

echo "2. FRONTEND ADMIN (Netlify):"
echo "   - Go to https://app.netlify.com"
echo "   - Find your site or create new from GitHub"
echo "   - Repository: https://github.com/KarmaliteHub/vehicle-sales-app"
echo "   - Base directory: frontend-admin"
echo "   - Build command: npm run build:prod"
echo "   - Publish directory: dist/frontend-admin"
echo "   - Environment variables:"
echo "     * API_URL=https://webvehicles-backend.onrender.com/api"
echo "   - Deploy the site"
echo ""

echo "3. FRONTEND WEB (Netlify):"
echo "   - Go to https://app.netlify.com"
echo "   - Find your site or create new from GitHub"
echo "   - Repository: https://github.com/KarmaliteHub/vehicle-sales-app"
echo "   - Base directory: frontend-web"
echo "   - Build command: npm run build"
echo "   - Publish directory: dist/frontend-web"
echo "   - Environment variables:"
echo "     * API_URL=https://webvehicles-backend.onrender.com/api"
echo "   - Deploy the site"
echo ""

echo "4. VERIFY DEPLOYMENT:"
echo "   - Backend health: https://webvehicles-backend.onrender.com/api/health/"
echo "   - Social media API: https://webvehicles-backend.onrender.com/api/social-media/public/"
echo "   - Frontend Admin: https://vehicle-sales-admin.netlify.app"
echo "   - Frontend Web: https://vehicle-sales-web.netlify.app"
echo ""

echo "5. POPULATE INITIAL DATA:"
echo "   - SSH into Render backend or use Render shell"
echo "   - Run: python manage.py populate_initial_configs"
echo "   - Run: python manage.py populate_social_media"
echo ""

echo "✅ All configuration files have been updated with the correct URLs"
echo "📝 Manual deployment steps are required on Render and Netlify platforms"
echo ""

echo "🔍 TROUBLESHOOTING:"
echo "If social media doesn't appear in frontend-web:"
echo "1. Check browser console for API errors"
echo "2. Verify backend is responding: curl https://webvehicles-backend.onrender.com/api/health/"
echo "3. Test social media endpoint: curl https://webvehicles-backend.onrender.com/api/social-media/public/"
echo "4. Check CORS settings in backend/backend/settings.py"
echo "5. Use test-frontend-social-media.js in browser console for debugging"