# Generated by Django 4.2.17 on 2026-03-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_systemlog_systemconfiguration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featureditem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='featureditem',
            constraint=models.CheckConstraint(check=models.Q(('car__isnull', False), ('motorcycle__isnull', False), _connector='OR'), name='featured_item_has_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='featureditem',
            constraint=models.CheckConstraint(check=models.Q(('car__isnull', False), ('motorcycle__isnull', False), _negated=True), name='featured_item_single_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='featureditem',
            constraint=models.UniqueConstraint(condition=models.Q(('car__isnull', False)), fields=('car',), name='unique_featured_car'),
        ),
        migrations.AddConstraint(
            model_name='featureditem',
            constraint=models.UniqueConstraint(condition=models.Q(('motorcycle__isnull', False)), fields=('motorcycle',), name='unique_featured_motorcycle'),
        ),
    ]
