"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 4.2.
"""

import os
import dj_database_url
from dotenv import load_dotenv
from datetime import timedelta
from pathlib import Path

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get('SECRET_KEY', 'Tk89HJNB1UMXrMD5igQg5eNNvzSKkigWyfd5BisrGedFa1S0L6ZB64d0SAzrxagmGrc')

DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1',
    '.onrender.com',
    'vehicle-sales-backend.onrender.com',
    'webvehicles-backend.onrender.com',
    'webvehicles.netlify.app',
    'vehicle-sales-admin.netlify.app',
    'vehicle-sales-frontend.netlify.app',
    'vehicle-sales-web.netlify.app',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'cloudinary_storage',  # Agregado para Cloudinary
    'cloudinary',          # Agregado para Cloudinary
    'vehicles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'vehicles.middleware.CircuitBreakerMiddleware',
    'vehicles.middleware.RetryMiddleware',
    'vehicles.middleware.DatabaseResilienceMiddleware',
    'vehicles.middleware.CorsHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Configuración de Base de Datos
# Si estamos en producción (Render), usar Supabase vía DATABASE_URL
# Si no, usar PostgreSQL local
if os.environ.get('ENVIRONMENT') == 'production' and os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
else:
    # Configuración local para desarrollo
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DATABASE_NAME', 'car_moto_sales'),
            'USER': os.environ.get('DATABASE_USER', 'car_moto_user'),
            'PASSWORD': os.environ.get('DATABASE_PASSWORD', 'securepassword123'),
            'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
            'PORT': os.environ.get('DATABASE_PORT', '5432'),
            'OPTIONS': {
                'connect_timeout': 10,
                'application_name': 'vehicle_app',
            }
        }
    }

# Connection pooling configuration (aplica para ambos entornos)
DATABASES['default']['CONN_MAX_AGE'] = 600
DATABASES['default']['CONN_HEALTH_CHECKS'] = True

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ============ CONFIGURACIÓN DE CLOUDINARY ============
# Importar Cloudinary siempre
import cloudinary
import cloudinary.uploader
import cloudinary.api

# Configurar Cloudinary con las variables de entorno
cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    api_key=os.environ.get('CLOUDINARY_API_KEY', ''),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET', ''),
    secure=True  # Asegurar que use HTTPS
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
    'SECURE': True,
}

# Usar Cloudinary en producción
if os.environ.get('ENVIRONMENT') == 'production' and CLOUDINARY_STORAGE['CLOUD_NAME']:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    # IMPORTANTE: NO definir MEDIA_URL cuando usas Cloudinary
    # Deja MEDIA_URL vacío o coméntalo
    MEDIA_URL = ''  # <--- ESTO ES CLAVE, dejarlo vacío
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# ============ CONFIGURACIÓN DE CORS ============
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://localhost:4201",
    "http://localhost:4300",
    "https://admincar.netlify.app",
    "https://webvehicles.netlify.app",
    "https://vehicle-sales-admin.netlify.app",
    "https://vehicle-sales-frontend.netlify.app",
    "https://vehicle-sales-web.netlify.app",
    "https://webvehiclespublic.netlify.app",
    "https://adminwebvehicles.netlify.app",
    # Agregar más dominios de Netlify que puedan estar en uso
    "https://webvehicles-admin.netlify.app",
    "https://webvehicles-web.netlify.app",
]

# Configuración adicional de CORS para mayor compatibilidad
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

# Headers permitidos
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Métodos permitidos
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Si hay variables de entorno para CORS, sobrescribir
if os.environ.get('CORS_ALLOWED_ORIGINS'):
    cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS').split(',')
    if cors_origins:
        CORS_ALLOWED_ORIGINS = cors_origins

# Configuración de logging para producción
if not DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'cloudinary': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }